// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"demo/bbs"
	"demo/bbs/controller"
	"demo/bbs/provider"
	"demo/bbs/service"
	"github.com/google/wire"
	"github.com/gutrse3321/aki-remote"
	"github.com/gutrse3321/aki/pkg/app"
	"github.com/gutrse3321/aki/pkg/config"
	"github.com/gutrse3321/aki/pkg/log"
	"github.com/gutrse3321/aki/pkg/transports/http"
	"github.com/gutrse3321/aki/pkg/transports/rpc"
)

// Injectors from wire.go:

func CreateApp(configPath string) (*app.Application, error) {
	viper, err := config.New(configPath)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	appOptions, err := bbs.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	serverOptions, err := rpc.NewServerOptions(viper)
	if err != nil {
		return nil, err
	}
	initServers := provider.CreateInitRpcServersFn()
	server, err := rpc.NewServer(serverOptions, logger, initServers)
	if err != nil {
		return nil, err
	}
	httpOptions, err := http.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	clientOptions, err := rpc.NewClientOptions(viper)
	if err != nil {
		return nil, err
	}
	client, err := rpc.NewClient(clientOptions)
	if err != nil {
		return nil, err
	}
	uCenterRemote, err := aki_remote.NewUCenterRemote(client)
	if err != nil {
		return nil, err
	}
	iUserService := service.NewUserService(uCenterRemote)
	indexController := controller.NewIndexController(iUserService)
	initControllers := controller.CreateInitControllersFn(indexController)
	engine := http.NewRouter(httpOptions, logger, initControllers)
	httpServer, err := http.New(httpOptions, logger, engine)
	if err != nil {
		return nil, err
	}
	application, err := bbs.NewApp(appOptions, logger, server, httpServer)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// wire.go:

/**
 * @Author: Tomonori
 * @Date: 2020/4/17 17:58
 * @Title:
 * --- --- ---
 * @Desc:
 */
var wireSet = wire.NewSet(log.WireSet, config.WireSet, http.WireSet, rpc.WireServerSet, rpc.WireClientSet, provider.ProviderSet, aki_remote.WireSet, bbs.ProviderSet, service.ProviderSet, controller.ProviderSet)
