app:
  name: ucenter

http:
  ip: 127.0.0.1
  port: 3000
  mode: debug

rpc:
  ip: 127.0.0.1
  port: 3000
  basePath: /rpcx_test
  updateInterval: 600000
  etcdAddress:
    - 175.24.110.208:2380

database:
  user: root
  password: 123456
  host: 127.0.0.1
  db: fuck
  maxIdleConns: 10
  maxOpenConns: 100
  debug: true

log:
  filename: /logtmp/ucenter.log
  maxSize: 500
  maxBackups: 3
  maxAge: 3
  level: "debug"
  stdout: false